### ISSUE TITLE
Run certain commands as specific users not ALL

### ISSUE THREAD

**Issue by indispeq** [Dsaad-People-Doc/ansible-sudoers#2]
It could be interesting to parameterise the user they are running it as. If the item does not exist a Jinja default could be `ALL`.  Should be enough to juste do `{{ item.user, 'ALL' }}`, if I recall correctly, but what would be interesting is how to rework the list of commands for some of them to be dicts and some to just be single list elements. Something to think about. The template could handle that logic.

**Comment by Dsaad-People-Doc** [comment]
Implemented! See merged Pull Request #3: https://github.com/Dsaad-People-Doc/ansible-sudoers/pull/3
